# Headless Service - No ClusterIP, for internal communication between pods in a StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
---
# Normal Service to allow trafice for internet to connect mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless" # this should be headless service
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  # This is nothing but PVC, you can directly create here
    # This ensures that each replica gets its own PersistentVolume (EBS disk, typically).
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi
